### ISSUE TITLE
Issues - Linux 

### ISSUE THREAD

**Issue by poyok8** [towai/TromboneCharter#1]
`copy section notes` causes the app to crash 
if you dont import a .tmb file you cannot make the section length <1 
Saving *sometimes* crashes 
First launch has no sound
`Copy to` crashes game 
Making the game full screen, and non full screen will make CPU usage spike

[NOTE] .exe version WORKS with wine

**Comment by towai** [comment]
> if you dont import a .tmb file you cannot make the section length <1

i'm assuming this is a typo but like, i should hope the program prevents you from making a 0-length / negative-length chart, lol

> [NOTE] .exe version WORKS with wine

i think this is just going to be the solution for the foreseeable future. it would be great to get this to work on linux natively, but as it stands, unless someone with a linux machine and godot knowledge really wants to get it functioning, it's probably not going to be usable on linux anytime soon. i'll leave this open, though.

**Comment by BNTFryingPan** [comment]
> unless someone with a linux machine and godot knowledge really wants to get it functioning
someone with a linux machine and godot knowledge has entered the room.

i was just messing around with this to try to chart a song, and i got it to save files properly as without modifications, it refuses to save if the path does not have a `:` in the second position. although i have yet to figure out how to use trombone charter properly yet so maybe i should figure that out before trying to fix all the issues.

**Comment by towai** [comment]
> it refuses to save if the path does not have a `:` in the second position.

yeah this tracks, I was doing a bunch of fiddling with the path to contend with inconsistencies in how Windows paths are expected in different functions, and provided by the FileDialogs (e.g. in signals, they provide the full path including the drive letter, whereas the path stored in current_dir/current_path properties omits the drive letter as of the most recent Godot 4 I was using). this makes it incompatible with other file systems, frustratingly. i think simply making that code only run on Windows machines would make it compatible again, but it might be interspersed with other code (i haven't looked at it in a hot second) so i would want to break it off into its own function. in fact when/if i ever come back to this the first thing i'll probably do is break the saving/loading stuff off into its own class, it's taken over the main scene's script quite a bit by this point

**Comment by towai** [comment]
So the path issue in particular has been fixed for a while now, as for the others

> copy section notes causes the app to crash
> First launch has no sound
> Copy to crashes game
> Making the game full screen, and non full screen will make CPU usage spike
> Saving sometimes crashes

I have not been able to reproduce any of these on my Linux laptop on the latest release build. There's other existing issues that may or may not have anything to do with Linux, but for now, closing this.
