### ISSUE TITLE
Simultaneous audio playback

### ISSUE THREAD

**Issue by RunDomRun** [towai/TromboneCharter#2]
Its not really an issue, but more of a feature that would make this great. If we could listen to the song while making the midi, it makes it much easier to make small changes and its just great for quality of life. Thanks!

**Comment by towai** [comment]
feature added in 105237e for 0.9.2! get the latest release and be sure to look at "info & usage" for details

**Comment by RunDomRun** [comment]
Sorry for bothering you again, but when I put the song.wav file in the same folder as the .tmb file, it says "no ffmpeg loaded!" What does this mean and how do I fix it?

**Comment by BodeMackie** [comment]
I have the same problem. I have tried everything I could think of to try and fix it, but nothing works
