### ISSUE TITLE
Win 64 issues

### ISSUE THREAD

**Issue by Birblord2087** [towai/TromboneCharter#3]
If trying to copy a section to an earlier point in the chart, Trombone Charter crashes on every attempt.

E.g. If I try to copy a section starting at beat 14 backwards to beat 13, it crashes. 

Pressing the "copy section lyrics" button crashes Trombone Charter if there are no lyrics.

(Otherwise this is an amazing piece of software, thank you for creating it!)

**Comment by Birblord2087** [comment]
Weirdly, this only seems to happen to certain songs. I'm not having any problems in the current one I'm working on, but another song crashed persistently... sorry, I'm not sure how to reproduce it accurately.

**Comment by towai** [comment]
I haven't been able to reproduce the crash on copy backward, but the crash on copy with no lyrics at all is fixed now. That one was absolutely my bad. Download the new release (when it's uploaded) and see if you can still reproduce the other one.

**Comment by towai** [comment]
OK, I found a way to reproduce the bug you were describing and I have a fix in the pipe along with generally improving the way section copy works. It'll be up soon.
