### ISSUE TITLE
maximum timing snap precision isn't precise enough

### ISSUE THREAD

**Issue by jummy0** [towai/TromboneCharter#5]
i need 1/16

**Comment by jummy0** [comment]
also it's weird that i can't even type it in.  even if i type 16 it resets to 1/12

**Comment by towai** [comment]
finally increased the max resolution in e3bd903faa406fd4b1bcf426d4284098bfbf268d.

it does affect the scoring... i think, but from a mapping standpoint if you find yourself needing to go below even 1/16ths it's possible that the more fitting option would be to double the BPM and compensate for it via the note spacing and the time signature (number of beats per white line)
