### ISSUE TITLE
Using horizontal scroll wheel doesn't show notes 

### ISSUE THREAD

**Issue by taihw** [towai/TromboneCharter#6]
TromboneCharter 0.95 x64, Windows 11.

When using my mouse's horizontal scroll wheel (thumb wheel on MX Master), notes in the section that I am scrolling into do not appear. I need to move the scrollbar or use the vertical scroll wheel (the standard wheel between LMB and RMB) for the notes to appear.

https://user-images.githubusercontent.com/16695146/203712792-e0ce5fd2-e05d-4f44-a79d-f0a86c89569d.mp4

**Comment by towai** [comment]
Fixed in #13
