### ISSUE TITLE
Song does not end, game freezes after last note

### ISSUE THREAD

**Issue by jbtcrh** [towai/TromboneCharter#7]
Hey there,

I've made a custom song with TromboneCharter. It can be opened and played, but at the end of the song the game soft locks: the end screen never shows up, the trombone can still be played, and the Escape key stops working, leaving only Alt+F4 as the last option to leave the game.
The BepinEx logs mention a missing file, but they do not specify which file is missing. The custom song folder has the song.tmb, song.ogg, song.wav and bg.png inside it. I've opened up the TMB file and compared it to a working custom song I found online, and couldn't notice any structural differences that would explain why my custom song is broken.

I've tried researching this problem but it seems that this hasn't really happened to anyone else. Do you have any idea what the game might be missing that causes it to fail right before the end screen?

Best,
Tom

**Comment by towai** [comment]
This can be caused by a few things iirc, but it's not a Trombone Charter issue. Usually it's caused by your song length being longer than your backing track. Either lower the endpoint value or add silence to the end of your bg.ogg.

**Comment by jbtcrh** [comment]
That was it, the endpoint was one bar too late. Thanks for the quick & helpful response!
